// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuMQXdqtqFPfTqz0cRCQnLwWR4KGhFWRs',
    appId: '1:63772006210:android:8b2c3eafaafac99cf05adb',
    messagingSenderId: '63772006210',
    projectId: 'diu-citizen',
    storageBucket: 'diu-citizen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi4dxPiEjCjxxbKCU-_RCaSFA1PlvK_P0',
    appId: '1:63772006210:ios:309c58353310d902f05adb',
    messagingSenderId: '63772006210',
    projectId: 'diu-citizen',
    storageBucket: 'diu-citizen.firebasestorage.app',
    iosBundleId: 'com.synergy.diuCitizen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi4dxPiEjCjxxbKCU-_RCaSFA1PlvK_P0',
    appId: '1:63772006210:ios:540fbfbfab423d0ff05adb',
    messagingSenderId: '63772006210',
    projectId: 'diu-citizen',
    storageBucket: 'diu-citizen.firebasestorage.app',
    iosBundleId: 'com.example.puri',
  );
}
